---
driver:
  name: vagrant
  use_sudo: false
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  policyfile_path: policies/vanilla.rb

platforms:
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04

suites:
  - name: vanilla
    provisioner:
      policyfile_path: policies/vanilla.rb
